### ISSUE TITLE
error when run `./gradlew gem` on EC2 instance

### ISSUE THREAD

**Issue by YutaroSoejima** [sakama/embulk-output-dynamodb#4]
### Environment
- ec2 t2.micro
- Embulk v0.8.8
- java version "1.7.0_101"
#### case `./gradlew gem`

```
Downloading https://services.gradle.org/distributions/gradle-2.10-bin.zip
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275/gradle-2.10-bin.zip to /root/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-2.10-bin/baigpnfu14tdk6ztbfwcl8275/gradle-2.10/bin/gradle
Download https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.pom
Download https://plugins.gradle.org/m2/com/github/jruby-gradle/jruby-gradle-plugin/0.1.5/jruby-gradle-plugin-0.1.5.pom
Download https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.2.1/httpcomponents-client-4.2.1.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/project/6/project-6.pom
Download https://plugins.gradle.org/m2/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Download https://plugins.gradle.org/m2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
Download https://plugins.gradle.org/m2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom
Download https://plugins.gradle.org/m2/org/apache/apache/3/apache-3.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.1/httpcore-4.2.1.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.2.1/httpcomponents-core-4.2.1.pom
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/5/commons-parent-5.pom
Download https://plugins.gradle.org/m2/org/apache/apache/4/apache-4.pom
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download https://plugins.gradle.org/m2/org/apache/apache/9/apache-9.pom
Download https://plugins.gradle.org/m2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/11/commons-parent-11.pom
Download https://plugins.gradle.org/m2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/9/commons-parent-9.pom
Download https://plugins.gradle.org/m2/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
Download https://plugins.gradle.org/m2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom
Download https://plugins.gradle.org/m2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom
Download https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.jar
Download https://plugins.gradle.org/m2/com/github/jruby-gradle/jruby-gradle-plugin/0.1.5/jruby-gradle-plugin-0.1.5.jar
Download https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.jar
Download https://plugins.gradle.org/m2/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Download https://plugins.gradle.org/m2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
Download https://plugins.gradle.org/m2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.1/httpcore-4.2.1.jar
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Download https://plugins.gradle.org/m2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar
Download https://plugins.gradle.org/m2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
Download https://plugins.gradle.org/m2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Download https://plugins.gradle.org/m2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar
Download https://plugins.gradle.org/m2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
:compileJava
Download https://jcenter.bintray.com/org/embulk/embulk-core/0.8.2/embulk-core-0.8.2.pom
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-dynamodb/1.10.50/aws-java-sdk-dynamodb-1.10.50.pom
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-pom/1.10.50/aws-java-sdk-pom-1.10.50.pom
Download https://jcenter.bintray.com/org/embulk/guice-bootstrap/0.1.1/guice-bootstrap-0.1.1.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://repo1.maven.org/maven2/com/google/inject/guice/4.0/guice-4.0.pom
Download https://repo1.maven.org/maven2/com/google/inject/guice-parent/4.0/guice-parent-4.0.pom
Download https://repo1.maven.org/maven2/com/google/google/5/google-5.pom
Download https://repo1.maven.org/maven2/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.pom
Download https://repo1.maven.org/maven2/com/google/inject/extensions/extensions-parent/4.0/extensions-parent-4.0.pom
Download https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.5.1/jackson-parent-2.5.1.pom
Download https://repo1.maven.org/maven2/com/fasterxml/oss-parent/19/oss-parent-19.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.5.3/jackson-datatype-guava-2.5.3.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.5.3/jackson-datatype-joda-2.5.3.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-guice/2.5.3/jackson-module-guice-2.5.3.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.1.3/logback-parent-1.1.3.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.0.4.0/jruby-complete-9.0.4.0.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-artifacts/9.0.4.0/jruby-artifacts-9.0.4.0.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-parent/9.0.4.0/jruby-parent-9.0.4.0.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.pom
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.14/snakeyaml-1.14.pom
Download https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.pom
Download https://repo1.maven.org/maven2/org/apache/bval/bval-jsr303/0.5/bval-jsr303-0.5.pom
Download https://repo1.maven.org/maven2/org/apache/bval/bval-parent/0.5/bval-parent-0.5.pom
Download https://repo1.maven.org/maven2/org/apache/apache/10/apache-10.pom
Download https://repo1.maven.org/maven2/io/airlift/slice/0.9/slice-0.9.pom
Download https://repo1.maven.org/maven2/io/airlift/airbase/21/airbase-21.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Download https://repo1.maven.org/maven2/joda-time/joda-time/2.8.1/joda-time-2.8.1.pom
Download https://repo1.maven.org/maven2/io/netty/netty-buffer/5.0.0.Alpha1/netty-buffer-5.0.0.Alpha1.pom
Download https://repo1.maven.org/maven2/io/netty/netty-parent/5.0.0.Alpha1/netty-parent-5.0.0.Alpha1.pom
Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.pom
Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi-project/1.11/jansi-project-1.11.pom
Download https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.8/fusesource-pom-1.8.pom
Download https://repo1.maven.org/maven2/org/msgpack/msgpack-core/0.8.1/msgpack-core-0.8.1.pom
Download https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.pom
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.10.50/aws-java-sdk-s3-1.10.50.pom
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.10.50/aws-java-sdk-core-1.10.50.pom
Download https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.pom
Download https://repo1.maven.org/maven2/org/apache/bval/bval-core/0.5/bval-core-0.5.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
Download https://repo1.maven.org/maven2/io/netty/netty-common/5.0.0.Alpha1/netty-common-5.0.0.Alpha1.pom
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/1.10.50/aws-java-sdk-kms-1.10.50.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/28/commons-parent-28.pom
Download https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.3.6/httpcomponents-client-4.3.6.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/7/project-7.pom
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils-core/1.8.3/commons-beanutils-core-1.8.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.3.3/httpcomponents-core-4.3.3.pom
Download https://jcenter.bintray.com/org/embulk/embulk-core/0.8.2/embulk-core-0.8.2.jar
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-dynamodb/1.10.50/aws-java-sdk-dynamodb-1.10.50.jar
Download https://jcenter.bintray.com/org/embulk/guice-bootstrap/0.1.1/guice-bootstrap-0.1.1.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
Download https://repo1.maven.org/maven2/com/google/inject/guice/4.0/guice-4.0.jar
Download https://repo1.maven.org/maven2/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.jar
Download https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.5.3/jackson-datatype-guava-2.5.3.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.5.3/jackson-datatype-joda-2.5.3.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-guice/2.5.3/jackson-module-guice-2.5.3.jar
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar
Download https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.0.4.0/jruby-complete-9.0.4.0.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar
Download https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
Download https://repo1.maven.org/maven2/org/apache/bval/bval-jsr303/0.5/bval-jsr303-0.5.jar
Download https://repo1.maven.org/maven2/io/airlift/slice/0.9/slice-0.9.jar
Download https://repo1.maven.org/maven2/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar
Download https://repo1.maven.org/maven2/io/netty/netty-buffer/5.0.0.Alpha1/netty-buffer-5.0.0.Alpha1.jar
Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.jar
Download https://repo1.maven.org/maven2/org/msgpack/msgpack-core/0.8.1/msgpack-core-0.8.1.jar
Download https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.10.50/aws-java-sdk-s3-1.10.50.jar
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.10.50/aws-java-sdk-core-1.10.50.jar
Download https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar
Download https://repo1.maven.org/maven2/org/apache/bval/bval-core/0.5/bval-core-0.5.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
Download https://repo1.maven.org/maven2/io/netty/netty-common/5.0.0.Alpha1/netty-common-5.0.0.Alpha1.jar
Download https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/1.10.50/aws-java-sdk-kms-1.10.50.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils-core/1.8.3/commons-beanutils-core-1.8.3.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 15.711 secs
```
#### case `./gradlew gem --stacktrace`

```
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.IllegalStateException: Could not find tools.jar
    at org.gradle.internal.jvm.JdkTools.<init>(JdkTools.java:57)
    at org.gradle.internal.jvm.JdkTools.current(JdkTools.java:44)
    at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory$SystemJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:77)
    at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory$SystemJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:75)
    at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.findCompiler(JavaHomeBasedJavaCompilerFactory.java:57)
    at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:44)
    at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:28)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:55)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:44)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
    at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 60 more


BUILD FAILED

Total time: 9.008 secs
```
#### case `/gradlew gem --info`

```
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/home/ec2-user/embulk-output-dynamodb/build.gradle'.
Included projects: [root project 'embulk-output-dynamodb']
Evaluating root project 'embulk-output-dynamodb' using build file '/home/ec2-user/embulk-output-dynamodb/build.gradle'.
All projects evaluated.
Selected primary task 'gem' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':assemble', task ':checkstyleMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':test', task ':check', task ':build', task ':classpath', task ':gemspec', task ':gem']
:compileJava (Thread[main,5,main]) started.
:compileJava
Executing task ':compileJava' (up-to-date check took 0.802 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':compileJava'.
Compiling with JDK Java compiler API.
:compileJava FAILED
:compileJava (Thread[main,5,main]) completed. Took 0.929 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 9.036 secs
Stopped 0 compiler daemon(s).
```

---

Sorry to bother you, but I'd like you to help me.
If you need more info, please ask me. I'll try it.

**Comment by sakama** [comment]
@YutaroSoejima Thanks for your reporting😄  Please let me investigate the root cause.

Well...could you rewrite your report in english when you can?
Writing issue in japanse may block non-japanese contributors.
http://www.slideshare.net/tagomoris/how-to-createimprove-oss-products-and-its-community/13

**Comment by sakama** [comment]
@YutaroSoejima If you're using OpenJDK, please install following 2 packages.
Additionally please confirm that proper path is set at JAVA_HOME.
- java-1.7.0-openjdk
- java-1.7.0-openjdk-devel

I think java-1.7.0-openjdk doesn't contains a tools.jar and causes these errors.
I could reproduce the same error when I built with java-1.7.0-openjdk. But error never happend after I installed java-1.7.0-openjdk-devel.

**Comment by YutaroSoejima** [comment]
@sakama 

Thanks!
I'll try according to your advice and will report result.

And I done rewrite. Sorry about my cheap English...

**Comment by YutaroSoejima** [comment]
@sakama 

Above problem was solved! Thank you!
But other issue happen... I'll mention it after creating another new issue.

Thank you!
